class App:
    def __init__(self) -> None: ...
    async def run(self, _render_update) -> None: ...
    def update(self, _delta) -> object: ...
    def draw(self, _ctx) -> None: ...
    def background_update(self, _delta) -> None: ...
    def minimise(self) -> None: ...
