class ePin:
    IN: int
    OUT: int
    PWM: int

    def __init__(self, *_args, **_kwargs) -> None: ...
    def init(self, *_args, **_kwargs) -> None: ...
    def value(self, *_args) -> int: ...
    def duty(self, *_args) -> int: ...
    def deinit(self) -> None: ...
