from typing import Protocol


class HexDriveLike(Protocol):
    def initialise(self) -> bool: ...
    def set_motors(self, outputs: tuple[int, ...]) -> bool: ...
    def set_power(self, state: bool) -> bool: ...
    def set_keep_alive(self, period: int) -> None: ...
    def set_freq(self, freq: int, channel: int | None = None, servo: bool = False) -> bool: ...
