from typing import Any

class Pin:
    IN: int
    OUT: int
    PWM: int
    IRQ_FALLING: int

    def __init__(self, *_args: Any, **_kwargs: Any) -> None: ...
    def init(self, *_args: Any, **_kwargs: Any) -> None: ...
    def value(self, *_args: Any) -> int: ...

class PWM:
    def __init__(self, _pin: Pin, *_args: Any, **_kwargs: Any) -> None: ...
    def freq(self, *_args: Any) -> int: ...
    def duty_u16(self, *_args: Any) -> int: ...
    def duty_ns(self, *_args: Any) -> int: ...
    def deinit(self) -> None: ...

class I2C:
    def __init__(self, *_args: Any, **_kwargs: Any) -> None: ...
    def scan(self) -> list[int]: ...
    def readfrom_mem(self, _addr: int, _memaddr: int, _nbytes: int, *_args: Any, **_kwargs: Any) -> bytes: ...
    def writeto_mem(self, _addr: int, _memaddr: int, _buf: bytes, *_args: Any, **_kwargs: Any) -> None: ...
    def writeto(self, _addr: int, _buf: bytes, _stop: bool = True) -> int: ...
    def readfrom(self, _addr: int, _nbytes: int, _stop: bool = True) -> bytes: ...

class UART:
    def __init__(self, *_args: Any, **_kwargs: Any) -> None: ...
    def readline(self) -> bytes | None: ...
    def deinit(self) -> None: ...

class Timer:
    PERIODIC: int
    ONE_SHOT: int

    def __init__(self, _id: int = -1, /, *_args: Any, **_kwargs: Any) -> None: ...
    def init(self, *_args: Any, **_kwargs: Any) -> None: ...
    def deinit(self) -> None: ...

class _Mem32:
    def __getitem__(self, addr: int) -> int: ...
    def __setitem__(self, addr: int, value: int) -> None: ...

mem32: _Mem32

def disable_irq() -> int: ...
def enable_irq(_state: int) -> None: ...
