from typing import TypeVar

_T = TypeVar("_T", int, float, str, bytes, bool)

def const(x: _T) -> _T: ...
def mem_info(verbose: bool = False) -> None: ...
def qstr_info(verbose: bool = False) -> None: ...
def stack_use() -> int: ...
def heap_lock() -> None: ...
def heap_unlock() -> None: ...
def kbd_intr(chr: int) -> None: ...
def schedule(func: object, arg: object) -> None: ...
