def ticks_ms() -> int: ...
def ticks_diff(new: int, old: int) -> int: ...
def ticks_add(ticks: int, delta: int) -> int: ...
def sleep_ms(ms: int) -> None: ...
def ticks_us() -> int: ...
def sleep_us(us: int) -> None: ...