from typing import Any

def mount(partition: Any, mountpoint: str, readonly: bool = ...) -> None: ...
def umount(mountpoint: str) -> None: ...

class VfsLfs2:
    @staticmethod
    def mkfs(partition: Any) -> None: ...
